# Generated by Django 5.2.15 on 2026-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_model',
            field=models.CharField(choices=[('None', 'None'), ('fable-low', 'fable-low'), ('fable-medium', 'fable-medium'), ('fable-high', 'fable-high'), ('fable-xhigh', 'fable-xhigh'), ('fable-max', 'fable-max'), ('opus-low', 'opus-low'), ('opus-medium', 'opus-medium'), ('opus-high', 'opus-high'), ('opus-xhigh', 'opus-xhigh'), ('opus-max', 'opus-max'), ('sonnet-low', 'sonnet-low'), ('sonnet-medium', 'sonnet-medium'), ('sonnet-high', 'sonnet-high'), ('sonnet-xhigh', 'sonnet-xhigh'), ('sonnet-max', 'sonnet-max'), ('haiku', 'haiku'), ('gpt-5.6-terra-low', 'gpt-5.6-terra-low'), ('gpt-5.6-terra-medium', 'gpt-5.6-terra-medium'), ('gpt-5.6-terra-high', 'gpt-5.6-terra-high'), ('gpt-5.6-terra-xhigh', 'gpt-5.6-terra-xhigh'), ('gpt-5.6-terra-max', 'gpt-5.6-terra-max'), ('gpt-5.6-terra-ultra', 'gpt-5.6-terra-ultra'), ('gpt-5.6-luna-low', 'gpt-5.6-luna-low'), ('gpt-5.6-luna-medium', 'gpt-5.6-luna-medium'), ('gpt-5.6-luna-high', 'gpt-5.6-luna-high'), ('gpt-5.6-luna-xhigh', 'gpt-5.6-luna-xhigh'), ('gpt-5.6-luna-max', 'gpt-5.6-luna-max'), ('gpt-5.5-low', 'gpt-5.5-low'), ('gpt-5.5-medium', 'gpt-5.5-medium'), ('gpt-5.5-high', 'gpt-5.5-high'), ('gpt-5.5-xhigh', 'gpt-5.5-xhigh')], default='None', max_length=64, verbose_name='AI Model'),
        ),
    ]
