# Generated by Django 5.2.15 on 2026-09-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issue_start_target_datetime'),
        ('db', '0123_workitemaiusage'),
    ]

    operations = [
    ]
