# Generated by Django 5.2.15 on 2026-09-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issue_ai_model'),
        ('db', '0124_merge_20260916_2323'),
    ]

    operations = [
    ]
