# Generated by Django 5.2.15 on 2026-09-18 19:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify

AWAITING_HUMAN_STATE = {"name": "Awaiting Human", "color": "#8E4EC6", "group": "started"}


def awaiting_human_state_sequence(states):
    """Place Awaiting Human right after the last started state (In Progress, Error), before the next state."""
    started = [state.sequence for state in states if state.group == "started"]
    if not started:
        return max((state.sequence for state in states), default=0) + 15000
    after = max(started)
    following = [state.sequence for state in states if state.sequence > after]
    return (after + min(following)) / 2 if following else after + 15000


def add_awaiting_human_state(apps, schema_editor):
    Project = apps.get_model("db", "Project")
    State = apps.get_model("db", "State")
    name = AWAITING_HUMAN_STATE["name"]
    new_states = []
    for project in Project.objects.filter(deleted_at__isnull=True).iterator():
        states = list(State.objects.filter(project_id=project.id, deleted_at__isnull=True))
        if any(state.name.casefold() == name.casefold() for state in states):
            continue
        new_states.append(
            State(
                name=name,
                slug=slugify(name),
                color=AWAITING_HUMAN_STATE["color"],
                group=AWAITING_HUMAN_STATE["group"],
                sequence=awaiting_human_state_sequence(states),
                project_id=project.id,
                workspace_id=project.workspace_id,
                created_by_id=project.created_by_id,
            )
        )
    State.objects.bulk_create(new_states, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_add_error_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('approval', 'Approval'), ('question', 'Question')], max_length=20)),
                ('question', models.TextField()),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.TextField(blank=True, default='')),
                ('decision', models.CharField(blank=True, choices=[('accept', 'Accept'), ('deny', 'Deny'), ('answered', 'Answered')], default='', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_requests', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_requests_asked', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('state_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_requests_before', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Human Request',
                'verbose_name_plural': 'Human Requests',
                'db_table': 'human_requests',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.RunPython(add_awaiting_human_state, migrations.RunPython.noop),
    ]
