# Generated by Django 5.2.15 on 2026-09-18 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from plane.utils.ai_pricing import compute_cost


def copy_work_item_ai_usage(apps, schema_editor):
    """Copy every WorkItemAIUsage row (soft-deleted ones too) into AIUsageRecord.

    The old rows do not say which cache TTL was written, so all cache writes
    count as 1h and the row is flagged ``split_unknown``. Records reuse the old
    row id, so running the copy again skips rows that were already copied.
    """
    WorkItemAIUsage = apps.get_model("db", "WorkItemAIUsage")
    AIUsageRecord = apps.get_model("db", "AIUsageRecord")
    copied = set(AIUsageRecord._base_manager.values_list("id", flat=True))
    records = []
    timestamps = []
    for usage in WorkItemAIUsage._base_manager.select_related("issue").iterator():
        if usage.id in copied:
            continue
        api_cost_usd, price_version = compute_cost(
            usage.model,
            input_tokens=usage.input_tokens,
            cache_write_1h_tokens=usage.cache_creation_input_tokens,
            cache_read_tokens=usage.cache_read_input_tokens,
            output_tokens=usage.output_tokens,
        )
        records.append(
            AIUsageRecord(
                id=usage.id,
                issue_id=usage.issue_id,
                issue_title=(usage.issue.name or "")[:255],
                session_id=usage.session_id,
                model=usage.model,
                input_tokens=usage.input_tokens,
                cache_write_1h_tokens=usage.cache_creation_input_tokens,
                cache_read_tokens=usage.cache_read_input_tokens,
                output_tokens=usage.output_tokens,
                api_cost_usd=api_cost_usd,
                price_version=price_version,
                split_unknown=True,
                external_source=usage.external_source,
                external_id=usage.external_id,
                project_id=usage.project_id,
                workspace_id=usage.workspace_id,
                created_by_id=usage.created_by_id,
                updated_by_id=usage.updated_by_id,
                deleted_at=usage.deleted_at,
            )
        )
        timestamps.append((usage.id, usage.created_at, usage.updated_at))
    AIUsageRecord._base_manager.bulk_create(records, batch_size=500)
    # auto_now_add/auto_now overwrite the timestamps on insert; restore the originals.
    for record_id, created_at, updated_at in timestamps:
        AIUsageRecord._base_manager.filter(id=record_id).update(created_at=created_at, updated_at=updated_at)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0126_add_error_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("issue_title", models.CharField(blank=True, default="", max_length=255)),
                ("session_id", models.CharField(blank=True, default="", max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("effort", models.CharField(blank=True, default="", max_length=32)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("cache_write_5m_tokens", models.PositiveBigIntegerField(default=0)),
                ("cache_write_1h_tokens", models.PositiveBigIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("usage_5h_pct", models.FloatField(blank=True, null=True)),
                ("usage_weekly_pct", models.FloatField(blank=True, null=True)),
                ("api_cost_usd", models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ("price_version", models.CharField(blank=True, default="", max_length=32)),
                ("split_unknown", models.BooleanField(default=False)),
                ("external_source", models.CharField(blank=True, max_length=255, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to="db.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Record",
                "verbose_name_plural": "AI Usage Records",
                "db_table": "ai_usage_records",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["created_at"], name="ai_usage_record_created_idx"),
                    models.Index(fields=["project", "created_at"], name="ai_usage_record_proj_crt_idx"),
                ],
            },
        ),
        migrations.RunPython(copy_work_item_ai_usage, migrations.RunPython.noop),
    ]
