# Generated by Django 5.2.15 on 2026-09-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_awaiting_human'),
        ('db', '0128_aiusagerecord'),
    ]

    operations = [
    ]
