# Generated by Django 5.2.15 on 2026-09-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_drop_workitemaiusage'),
        ('db', '0129_merge_0127_awaiting_human_0128_aiusagerecord'),
    ]

    operations = [
    ]
