# Generated by Django 5.2 on 2026-09-20

from django.db import migrations, models


EFFORTS = ("low", "medium", "high", "xhigh", "max")
VALUES = (
    ["None"]
    + [f"{name}-{effort}" for name in ("fable", "opus", "sonnet") for effort in EFFORTS]
    + ["haiku"]
    + [f"gpt-6-astra-{effort}" for effort in EFFORTS]
    + [f"gpt-5.6-sol-{effort}" for effort in EFFORTS]
    + [f"gpt-5.6-terra-{effort}" for effort in (*EFFORTS, "ultra")]
    + [f"gpt-5.6-luna-{effort}" for effort in EFFORTS]
    + [f"gpt-5.5-{effort}" for effort in EFFORTS[:4]]
)


class Migration(migrations.Migration):
    dependencies = [("db", "0131_remove_error_state")]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="ai_model",
            field=models.CharField(
                choices=[(value, value) for value in VALUES],
                default="None",
                max_length=64,
                verbose_name="AI Model",
            ),
        )
    ]
